# Generated by Django 6.0.2 on 2026-02-16 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0002_alter_document_options_alter_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentactivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Document Activity', 'verbose_name_plural': 'Document Activities'},
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_activities', to='accounts.department'),
        ),
    ]
