# Generated by Django 6.0.2 on 2026-02-19 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0003_alter_documentactivity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentactivity',
            name='action',
            field=models.CharField(choices=[('view', 'Viewed'), ('create', 'Created'), ('edit', 'Edited'), ('delete', 'Deleted'), ('attempt_disabled', 'Attempted Disabled Access')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['department'], name='documents_d_departm_42fae4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['action'], name='documents_d_action_79226c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['timestamp'], name='documents_d_timesta_37a050_idx'),
        ),
    ]
