# Generated by Django 6.0.2 on 2026-02-20 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentactivity_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='readers',
            field=models.ManyToManyField(blank=True, help_text='Specific users allowed to read this document.', related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
